### ISSUE TITLE
Add option to enable culling

### ISSUE THREAD

**Issue by hydino2085143** [gliscowo/isometric-renders#25]
Many isometric renders of closed spaces remove certain walls in order to show the interior, e.g as below
![image](https://user-images.githubusercontent.com/46134462/167993749-41000860-a1c1-4290-94c4-584fbeedf3db.png)

However, when rendering a closed or underground space, the buildings are obscured by stone or other wall materials.
![area_render_9](https://user-images.githubusercontent.com/46134462/167994289-ee21a70a-77eb-479d-b4b9-78c59ff30fe7.png)
 
 With this in mind, is it possible to add an option to cull chosen surfaces/blocks?

**Comment by gliscowo** [comment]
This issue is in no way a trivial addition and I argue there is no real value in it. It would be difficult to properly design an interface that lets you choose which blocks to cull and which ones to keep - it is significantly easier and more straight-forward to simply remove the blocks in question from the world before rendering. I appreciate the kind of look you're going for, but you can very much achieve it in the current version of Isorenders and it's not really feasible to control culling in the way required to make this work

Cheers
